import {
  BROWSER_ACP_APP_SUPPORT_DIR_NAME,
  BROWSER_ACP_EXTENSION_NAME,
  BROWSER_ACP_NATIVE_HOST_NAME,
} from "@browser-acp/config";

export const BROWSER_ACP_ROOT_DIR_NAME = BROWSER_ACP_APP_SUPPORT_DIR_NAME;
export const BROWSER_ACP_EXTENSION_DISPLAY_NAME = BROWSER_ACP_EXTENSION_NAME;
export const NATIVE_HOST_NAME = BROWSER_ACP_NATIVE_HOST_NAME;
export const NATIVE_HOST_DESCRIPTION = "Native messaging host for the Browser ACP side panel";
